### ISSUE TITLE
Live unit testing

### ISSUE THREAD

**Issue by Xorpio** [koenbeuk/ScenarioTests#17]
Live Unit Testing does not seem to discover the generated unit tests. This also applies to right clicking in the source and hitting Test/Debug.

Steps to reproduce:
* Checkout this repository.
* Open BasicSample
* Open TheoriesHaveTheriLimits
* Right click on line 28: 
![image](https://user-images.githubusercontent.com/3060868/126452616-b2e7e010-762f-42da-a9d3-e0c338f10e07.png)

* hit: ![image](https://user-images.githubusercontent.com/3060868/126452215-3a35ce72-120d-4372-8062-ae3f4d552338.png)

**Comment by koenbeuk** [comment]
@Xorpio The Live Unit Test issue is a known issue related to VS and can be followed here: https://developercommunity2.visualstudio.com/t/Live-unit-testing-does-not-work-with-Sou/1476580?entry=problem&ref=native&refTime=1626870821720&refUserId=3c4f7722-aa19-6161-a245-cf0086970d0e

Regarding being able to right click and start/debug a test: This is also a known limitation at the moment. I'm not sure if there is an easy fix however at the moment, VS is unable to map the Scenario method to the generated test cases. You either have to go to the generated code or start/debug a test from the Test explorer window. I will look into this further

**Comment by koenbeuk** [comment]
I'm leaving this open as I'm waiting for a resolution from the VS related issue.

**Comment by koenbeuk** [comment]
I can confirm that this is now working for me in the latest preview release of VS 2022.
